### ISSUE TITLE
Chrome Developer Tools

### ISSUE THREAD

**Issue by selimhex** [oelna/hsma-html#42]
Accessibility Simulationen: https://twitter.com/mathias/status/1237393102635012101

Instagram nachrichten am PC #hack:
auf Instagram : Dev Tools>mobile device wählen > refresh > mobile view und dadurch nachrichten sind am PC verfügbar:)

**Comment by Herr-ka** [comment]
WOW! Krasses Tool!
Damit kann man sogar Posten! ;)

**Comment by oelna** [comment]
> WOW! Krasses Tool!
> Damit kann man sogar Posten! ;)

Na klar. 40 super interessante Beiträge hier und du findest natürlich den Instagram Tip geil. 🤦🏻‍♂️
Normal hätt ichs gelöscht, aber weils eigentlich um die Vision deficiencies geht lass ichs mal durchgehen. Vielleicht lohnt sich das in der Stunde für die Erstsemester zu erwähnen, wos um die Dev Tools und Barrierefreiheit für `<img />` geht.

**Comment by selimhex** [comment]
Na ja, es geht generell um die Chrome Dev Tools:)

Accessibility Feature ist super relevant. Developers sollten ja nicht nur unterschiedliche _Geräte_ unterstützen...

Aber kleine hacks wie https://github.com/oelna/hsma-html/issues/42#issue-578673573 sollten unter diesem Thema gennant werden dürfen. Vor allem, weil dieses zentrales Feature von der App den Nutzern am PC einfach nicht angeboten wird.(Nachrichten)

Ich glaube auch, dass du es jetzt nicht irrelevant findest, z.B. eine Paywall vor einem Zeitungsartikel mit einer kleinen CSS injection weg zu machen. Wissen will raus!:P

**Comment by oelna** [comment]
Ich finde ja nicht den Tip generell verkehrt, sondern dass er in dieses issue mit rein gemischt wird. Ich sehe das hier eher als dauerhafte Referenz für Sachen, die es bisher nicht in die Kursstunden reingeschafft haben. Instagram verändert sich ständig. Da gehst du doch nicht in ein paar Jahren hierher zurück und passt die Information an, oder? :)

**Comment by selimhex** [comment]
Ich glaube in ein paar Jahren wird es trotzdem genug schlecht gemachte Apps geben. Man kann dieses Wissen, in der Zukunft gerne bei anderen Sachen anwenden. Hiermit erkläre ich noch https://github.com/oelna/hsma-html/issues/42#issue-578673573 für open-source und halal.

**Comment by oelna** [comment]
case closed
